enum SERVICE_TYPE {
  default_value = 0,
  custom_comments_value = 1,
  package_value = 2,
  invite_from_group_value = 3,
  subcription_reselling_value = 4,
  custom_comments_package_value = 5,
  mention_custom_list_value = 6,
  poll_value = 7,
  mentions_with_hashtags_value = 8,
  mentions_user_followers_value = 9,
  comment_likes_value = 10,
  mentions_hashtag_value = 11,
  mentions_media_likers_value = 12,
  default_label = "Default",
  custom_comments_label = "Custom Comments",
  package_label = "Package",
  invite_from_group_label = "Invites from Groups",
  subcription_reselling_label = "Subcription reselling",
  custom_comments_package_label = "Customs comments Package",
  mention_custom_list_label = "Mentions Custom List",
  poll_label = "Poll",
  mentions_with_hashtags_label = "Mentions with Hashtags",
  mentions_user_followers_label = "Mentions User Followers",
  comment_likes_label = "Comments Likes",
  mentions_hashtag_label = "Mentions Hashtag",
  mentions_media_likers_label = "Mentions Media Likers",
}

export { SERVICE_TYPE };
